<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="features_modeling" nsURI="http://www.example.org/features_modeling"
    nsPrefix="features_modeling">
  <eClassifiers xsi:type="ecore:EClass" name="G">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" lowerBound="1" eType="#//R"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        upperBound="-1" eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" lowerBound="1" eType="#//R"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="2"
        upperBound="2" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="#//Edge"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMAND" eSuperTypes="#//E"/>
  <eClassifiers xsi:type="ecore:EClass" name="GXOR" eSuperTypes="#//Group"/>
  <eClassifiers xsi:type="ecore:EClass" name="GOR" eSuperTypes="#//Group"/>
  <eClassifiers xsi:type="ecore:EClass" name="I" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="EX" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="2"
        upperBound="2" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        upperBound="-1" eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropFormulaCNF">
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposition" upperBound="-1"
        eType="#//PropositionOR" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AND"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropositionOR">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="not" upperBound="-1" eType="#//NOT"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NOT">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
